name: Monthly Report

on:
  schedule:
    - cron: "0 0 1 * *"  # Esegue il primo giorno di ogni mese a mezzanotte UTC
  workflow_dispatch:  # Permette l'esecuzione manuale del workflow

jobs:
  generate_report:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Aggiornato a Node.js 20

    - name: Set up Python 3.x
      uses: actions/setup-python@v3  # Aggiornato a Node.js 20
      with:
        python-version: '3.x'

    - name: Run Python script
      run: python main.py
