name: Run Data Collection and Analysis

on:
  schedule:
    # Esegue il workflow il primo giorno di ogni mese alle 00:00 UTC
    - cron: "0 0 1 * *"
workflow_dispatch:  # Permette l'esecuzione manuale del workflow


jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install yfinance pandas tqdm

    - name: Run Python script
      run: python main.py
